### ISSUE TITLE
ifconfig error

### ISSUE THREAD

**Issue by KiwiHC16** [johnthagen/pytap2#8]
Hi All,

On a deban RPI3, I tested the first proposed code:

```
root@host:~# cat test.py 
from pytap2 import TapDevice

with TapDevice() as device:
    device.ifconfig(mtu=1300)
    device.write(b'0000')
```

And I got an error:

```
root@host:~# python3 test.py 
sh: 1: ifconfig: not found
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    with TapDevice() as device:
  File "/usr/local/lib/python3.7/dist-packages/pytap2/__init__.py", line 90, in __enter__
    self.up()
  File "/usr/local/lib/python3.7/dist-packages/pytap2/__init__.py", line 213, in up
    raise IfconfigError()
pytap2.IfconfigError
```

This error was discover in the context of meshtatsic project: https://github.com/meshtastic/Meshtastic-python/issues/104

Any thing I can do ?

Thanks

KiwiHC16

**Comment by KiwiHC16** [comment]
```
pip install pytap2==2.0.0
pip install pytap2==1.6.0
pip install pytap2==1.5.0
pip install pytap2==1.4.0
pip install pytap2==1.3.0
```

Same issue on all releases ;-(

**Comment by KiwiHC16** [comment]
Doesn't work on Debian 10, Ubuntu and Raspbian 10. 
Is it in relation to the fact that ifconfig doesn't exist in the OS and is replaced by ip addr ?

**Comment by KiwiHC16** [comment]
https://linuxconfig.org/how-to-install-missing-ifconfig-command-on-debian-linux

**Comment by KiwiHC16** [comment]
pytap2 needs to be adapted for Debian distribution.

**Comment by johnthagen** [comment]
Also see https://pypi.org/project/python-pytun/ which looks like it might be more actively maintained.

And yes `ifconfig` needs to be installed for this project to work.

Have you tried:

```
sudo apt install net-tools
```

**Comment by KiwiHC16** [comment]
Yes 

sudo apt install net-tool

Is a solution. 

Thanks.

**Comment by johnthagen** [comment]
This system requirement has been documented in 684155b2a276aa243f300acd9cd346a3bafe7793
